### ISSUE TITLE
imwrite error on OS X 10.9

### ISSUE THREAD

**Issue by Koloth** [JuliaImages/Images.jl#144]
This may be related to #118 since I need to manually load Homebrew before Images to not get the ImageMagick error message.  When running `imwrite(grayim(rand(100,100)),"test.png")` or any other similar `imwrite` call, I get the following message (independent of file extension):

> ERROR: NoEncodeDelegateForThisImageFormat `MIFF' @ error/constitute.c/WriteImage/1164
> in error at error.jl:21
> in error at /Users/bwerness/.julia/Images/src/ioformats/libmagickwand.jl:116
> in writeimage at /Users/bwerness/.julia/Images/src/ioformats/libmagickwand.jl:198
> in imwrite at /Users/bwerness/.julia/Images/src/io.jl:163

I'm not sure it is relevant, but I have also experienced the error described in #120, but a reinstall of ImageMagick and the Images package seems to have fixed that.

**Comment by cormullion** [comment]
I had a similar issue this week, using Mac OS X ElCap and Julia 0.4rc2. Although ImageMagick appeared to work (`convert` at the command line works, for example), in Julia an `imwrite()` call fails with:

    ERROR: NoEncodeDelegateForThisImageFormat `MIFF' @ error/constitute.c/WriteImage/1164

After reading various remarks about possible duplicates, I deleted everything I could find containing the word "Magick", including `~/.julia/v0.4/Homebrew/deps/usr/Cellar/imagemagick`.

Then `Pkg.build("Images")` worked, and so did `imwrite`.

**Comment by rsrock** [comment]
@cormullion Glad you fixed it.  For anyone else that runs into this, one issue could be if you use your system Homebrew to install ImageMagick.  The Images build script will choose your system Homebrew version over the Julia Homebrew version.

The system Homebrew has a bunch of options for picking delegates at install time.  For example, TIFF is not a default delegate if I recall correctly.

**Comment by cstjean** [comment]
@cormullion I got the same error because of El Capitan, too, but I haven't solved it yet. What else have you deleted? I tried to rm ~/.julia/v0.4/Homebrew/deps/usr/Cellar/imagemagick then reinstalled it with Julia's brew, but it didn't fix the issue. Also of note, in addition to the MIFF error, when displaying an image I get:

```julia
> testimage("mandrill")

 in error at /Applications/Julia-0.4.1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in error at /Users/cedric/.julia/v0.4/ImageMagick/src/libmagickwand.jl:149
 in setimageformat at /Users/cedric/.julia/v0.4/ImageMagick/src/libmagickwand.jl:346
 in getblob at /Users/cedric/.julia/v0.4/ImageMagick/src/libmagickwand.jl:212
 in writemime_ at /Users/cedric/.julia/v0.4/ImageMagick/src/ImageMagick.jl:250
```
i.e. it doesn't even show an error message, but clearly something is wrong, and no image is output.

**Comment by staticfloat** [comment]
@cstjean Where is the `testimage()` function from?  I'm trying to test locally to see if my installation has the same problem.

**Comment by timholy** [comment]
`using TestImages`

**Comment by cstjean** [comment]
I've tried looking into `libmagickwand` and adding Tim's lines:
```julia
function writeimage(wand::MagickWand, filename::AbstractString)
    _, ext = splitext(filename)
    println(ext[2:end])
    setimageformat(wand, ext[2:end])
    status = ccall((:MagickWriteImages, libwand), Cint, (Ptr{Void}, Ptr{UInt8}, Cint), wand.ptr, filename, true)
    status == 0 && error(wand)
    nothing
end
```
This yields
```
WARNING: ErrorException("")
 in error at /Applications/Julia-0.4.1.app/Contents/Resources/julia/lib/julia/sys.dylib
 in error at /Users/cedric/.julia/v0.4/ImageMagick/src/libmagickwand.jl:149
 in setimageformat at /Users/cedric/.julia/v0.4/ImageMagick/src/libmagickwand.jl:349
 in writeimage at /Users/cedric/.julia/v0.4/ImageMagick/src/libmagickwand.jl:247
 in save_ at /Users/cedric/.julia/v0.4/ImageMagick/src/ImageMagick.jl:146
```
which looks like a bug in ImageMagick (they return an error, but the exception is unspecified), so maybe I can take it up with them. I suppose the next step might be to write some C code to demonstrate that something bad is happening.

I assume that reinstalling Julia won't be useful? ImageMagick is installed in Julia's Homebrew directory, but reinstalling it makes no difference (and I've confirmed that it doesn't work at all when uninstalled), and it seems like a clean setup. The configuration files seem to be read at the correct place:
```
> ls /Users/cedric/.julia/v0.4/Homebrew/deps/usr/Cellar/imagemagick/6.9.2-6/etc/ImageMagick-6
coder.xml		mime.xml		type-ghostscript.xml
colors.xml		policy.xml		type-windows.xml
delegates.xml		quantization-table.xml	type.xml
log.xml			thresholds.xml
magic.xml		type-dejavu.xml
```
although I've messed with the code enough that now `display(img)` yields `nothing` instead of an error, in spite of `Pkg.build` calls. So it seems that the code can get borked in other ways too.

**Comment by timholy** [comment]
@cstjean, I wonder if it would just be easier to extend QuartzImageIO to support writing? ImageMagick seems perpetually painful for OSX users. I wouldn't be surprised if it were a 1-day project. But since I don't have a mac, it won't be me spending that 1 day.

I don't know whether the design of the OSX library supports implementing `writemime`; that's what you seem to need here, since the errors are only cropping up when you try to display the images. You must be using IJulia or something?

**Comment by cstjean** [comment]
@timholy If it helps others, I'm happy to spend some time on QuartzImageIO.

I do use IJulia, yes. Before my last Pkg.update (which dragged a ton of Homebrew updates due to El Capitan) images would display just fine. After the update, `display(img)` would yield the `error at /Applications/Julia-0.4.1.app/Contents/Resources/julia/lib/julia/sys.dylib` mentionned above. Today, it yields `nothing`, which to me suggests that I've messed something extra on the Julia side of thing.

In any case, `imwrite`/`save("test.png", img)` fails with the `MIFF` error, and that should be unrelated to IJulia.

**Comment by cstjean** [comment]
Oh, sorry - I was using `img = load("~/test.png")`, and it seems that A) `load` does not recognize `~` and B) `load` returns `nothing` if the file is not found instead of an Exception. So I don't have an IJulia problem, just an ImageMagick problem. I'll look into Quartz.

**Comment by timholy** [comment]
Hmm, seems like it should throw an exception. I get this:
```
julia> load("~/test.png")
WARNING: ErrorException("unable to open file `~/test.png' @ error/png.c/ReadPNGImage/3667")
 in error at ./error.jl:21
 in error at /home/tim/.julia/v0.4/ImageMagick/src/libmagickwand.jl:149
 in readimage at /home/tim/.julia/v0.4/ImageMagick/src/libmagickwand.jl:228
 in load_ at /home/tim/.julia/v0.4/ImageMagick/src/ImageMagick.jl:75
 in load at /home/tim/.julia/v0.4/ImageMagick/src/ImageMagick.jl:63
 in load at /home/tim/.julia/v0.4/FileIO/src/loadsave.jl:77
 in load at /home/tim/.julia/v0.4/FileIO/src/loadsave.jl:42
ERROR: unable to open file `~/test.png' @ error/png.c/ReadPNGImage/3667
 in error at ./error.jl:21
 in error at /home/tim/.julia/v0.4/ImageMagick/src/libmagickwand.jl:149
 in readimage at /home/tim/.julia/v0.4/ImageMagick/src/libmagickwand.jl:228
 in load_ at /home/tim/.julia/v0.4/ImageMagick/src/ImageMagick.jl:75
 in load at /home/tim/.julia/v0.4/ImageMagick/src/ImageMagick.jl:63
 in load at /home/tim/.julia/v0.4/FileIO/src/loadsave.jl:77
 in load at /home/tim/.julia/v0.4/FileIO/src/loadsave.jl:42
```
But perhaps the difference is a working vs broken ImageMagick. Seems reasonable to think that FileIO should be throwing the error for a missing file...
