### ISSUE TITLE
Output in Juno

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaImages/Images.jl#435]
Images don't show up inline in Juno.  calling "view" opens another window.

**Comment by timholy** [comment]
`view` isn't a function in Images. What exactly are you trying?

**Comment by dlfivefifty** [comment]
That’s from ImageView I think.  But I expected the image to just show up automatically, without the “view” call.

**Comment by timholy** [comment]
If you want it to show up automatically in something that knows how to display mime types, you don't need to say `using ImageView`. Last time I tried it, this works in IJulia, but I haven't played with Juno.

However, there is a chance you need to say `using ImageMagick` to get it to work, since I think the `writemime` functionality got moved there.

**Comment by ChrisRackauckas** [comment]
Updating this now that things have changed. To use the Juno plot pane, a render command has to be implemented using the Juno.jl frontend package. Would adding this methods + the dependency to ImageView be something of interest?

**Comment by jianghaizhu** [comment]
Any update on this? Can we display images automatically in the Plot pane in JUNO now?

**Comment by timholy** [comment]
Sorry I missed @ChrisRackauckas's comment. Yes, this is definitely interesting. I tried adding the following to Images/src/showmime.jl:
```julia
@require Media begin
    Media.media(ColorantMatrix, Media.Graphical)
    @require Atom begin
        function Media.render(pane::Atom.PlotPane, img::ColorantMatrix)
            Media.render(pane, Atom.div(".fill", Atom.HTML(stringmime(MIME("image/png"), img))))
        end
    end
end
```
but that didn't work (image dumped to Juno's console rather than the PlotPane) even though I got
![image](https://user-images.githubusercontent.com/1525481/27515242-9a879506-5964-11e7-828c-c4af6f173c38.png)

I also tried `Media.Image` rather than `Media.Graphical`, with no change. If I put a debugging statement into those functions they aren't called. If I change `Atom.PlotPane` to `Juno.Inline`, then I can see the method is called but it just dumps the base64 to the console. Any thoughts? CC @MikeInnes.

**Comment by pfitzseb** [comment]
That's actually a Juno issue (which I'm amazed no one has found yet), which should be fixed with https://github.com/JunoLab/Atom.jl/pull/93. In the meantime you could eval the code from an editor, which will call the correct `render` methods.

The above `render` method will also only dump the Base64 encoded image into the plot pane, but I can look into proper image rendering tonight/tomorrow unless someone beats me to it (in theory GR or Plots or similar should have the correct code for this, I think?).

**Comment by pfitzseb** [comment]
```julia
using Images, Requires

@require Juno begin
    import Hiccup, Media
    Media.media(Images.ColorantMatrix, Media.Graphical)

    function Juno.render(e::Juno.Editor, img::Images.ColorantMatrix)
        Juno.render(e, nothing)
    end

    function Juno.render(pane::Juno.PlotPane, img::Images.ColorantMatrix)
        Juno.render(pane, HTML("<img src=\"data:image/png;base64,$(stringmime(MIME("image/png"), img))\">"))
    end
end

img = rand(RGB{N0f8}, 256, 256)
```
![screenshot_20170702_183915](https://user-images.githubusercontent.com/6735977/27771795-c1fc905e-5f55-11e7-959b-1c56ef5c8c2f.png)

Not sure if having the base64 encoded image displayed inline is the best of ideas -- saving it to a temppath might be better (probably only relevant for big pictures).

**Comment by pfitzseb** [comment]
@timholy Where do you think the display code code should go? Images or ImageView?

**Comment by timholy** [comment]
Thanks for the bump!

I think it should go in Images. Does one really have to use `Requires`, though? If you're using Juno then won't that package be loaded first? In which case one can just put an
```julia
if isdefined(Main, :Juno)
    ...
end
```
in Images.jl's `__init__` function?

**Comment by pfitzseb** [comment]
That should work fine if `using Images` is issued in a running session, but not if it's in `.juliarc.jl`. As far as I understand Requires.jl is okay to use (i.e. there should be no issues with precompilation etc.), but if you don't want to use it then that's fine too.

I'll open a PR real quick and further discussion can take place there.

**Comment by tkelman** [comment]
> there should be no issues with precompilation

Well the requires code won't be precompiled. However on 0.5 it is quite flaky, are you sure you want to depend on requires even in an 0.5-supporting release?

**Comment by timholy** [comment]
Good point. I'll bump the minimum version.
