### ISSUE TITLE
Display error on IJulia notebook

### ISSUE THREAD

**Issue by sunilnayak133** [JuliaImages/Images.jl#462]
I was running the fft method on an image I loaded into the variable 'c', and it resulted in the error below.

``` julia
l = fft(float64(c))
MethodError: `mapinfo` has no method matching mapinfo(::Type{FixedPointNumbers.UFixed{UInt8,8}}, ::Images.Image{Complex{Float64},3,Array{Complex{Float64},3}})
Closest candidates are:
  mapinfo(::Type{FixedPointNumbers.UFixed{UInt8,8}}, !Matched::Union{AbstractArray{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt8,8}},N},AbstractArray{FixedPointNumbers.UFixed{UInt8,8},N}})
  mapinfo(::Type{FixedPointNumbers.UFixed{UInt8,8}}, !Matched::Union{AbstractArray{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,10}},N},AbstractArray{FixedPointNumbers.UFixed{UInt16,10},N}})
  mapinfo(::Type{FixedPointNumbers.UFixed{UInt8,8}}, !Matched::Union{AbstractArray{ColorTypes.Gray{FixedPointNumbers.UFixed{UInt16,12}},N},AbstractArray{FixedPointNumbers.UFixed{UInt16,12},N}})
  ...

 in mapinfo_writemime at /Users/linus/.julia/v0.4/Images/src/writemime.jl:42
 in base64encode at base64.jl:160
 in display_dict at /Users/linus/.julia/v0.4/IJulia/src/execute_request.jl:32
```

This was run inside an IJulia Notebook, using the Julia 0.4.5 kernel.

cc: @rohitvarkey

**Comment by SimonDanisch** [comment]
Well, as you can see, the result type of fft is `Image{Complex}`, which can't be viewed directly. 
I'm not a 100% sure if this is the intended usage, but it seems to work:
```Julia
using FileIO, Images
img = load("...")
absolute_part = colorim(abs(fft(float64(img)))) # abs is defined for image directly but doesn't return an Image?
imaginary_part = colorim(imag(fft(float64(img)).data)) # imag doesn't seem to be defined for Image directly?
```

**Comment by rohitvarkey** [comment]
> Well, as you can see, the result type of fft is Image{Complex}, which can't be viewed directly.

Would it be a good idea to make these kind of images use a different `writemime` (maybe call `writemime` on the data?) rather than erroring out trying to display it?

Also I tried the `abs..` way to display the fft but I get an `InexactError()`.

**Comment by timholy** [comment]
If there's an obvious way to display it, then a custom writemime method would be fine. For example, for an fft of a grayscale image, I could imagine using one colorchannel for real and one for imaginary.

However, as soon as you think about an fft of an RGB image, there aren't enough color channels. So, for complex-valued images I recommend just using console-display (as with `show`). Since I don't use IJulia myself and have too many other commitments, this isn't a high priority of mine, so it will surely require a contribution from those for whom this matters.
