### ISSUE TITLE
Spatial Order Future

### ISSUE THREAD

**Issue by mronian** [JuliaImages/Images.jl#539]
While creating tests with real images for ORB and BRIEF, I realised that the `Image` type has the spatial order [x y] by default. Since I have been testing with hand made arrays, I have used the order [y x] in most functions (changing that right now in ImageFeatures.jl). To make sure, I went through all my PRs for Images.jl and almost all are fine (since they use `CartesianRange` to iterate) except for the following : 
[ ] `boxdiff`
[ ] `bilinear_interpolation`
[ ] `clahe`

I think `integral_image` is fine(https://github.com/timholy/Images.jl/pull/508/files#diff-77d828dbeb561ecf3e21705f067a485dR1963). @timholy Could you confirm?

Also, with the `JuliaImages`, do you plan on having the same spatial order?

**Comment by Evizero** [comment]
IMHO [y,x] should be the appropriate interpretation for plain arrays (It already is AFAIK, and I hope it will remain as such)

**Comment by mronian** [comment]
The representation for plain arrays is [y x] but the `Image` type changes the spatial order to [x y] due to which all functions have to be written to suit that order. The difference can be seen by - 
```jl
save("res.jpg", img)
save("res2.jpg", data(img))
```

**Comment by mronian** [comment]
This difference in spatial orders is creating a problem while porting tests to the [x y] order. How do I change a normal Array to Image with the switched spatial order?

**Comment by timholy** [comment]
My plan is to ignore this problem :smile:. The reason being that the rewrite of Images is getting pretty close---I estimate about a week of work to go. Solving this problem is perhaps the single biggest motivation for the rewrite, so I don't think it's worth worrying about this any longer within "classic" Images. (If anyone wants to try, go for it, but I won't spend any thought on it myself.)

In the new Images, my plan is that orientation is *always* determined by the order of dimensions---if you want to swap the order without actually computing the permutation, there is [`permuteddimsview`](https://juliaimages.github.io/ImagesCore.jl/latest/views/#Views-1) which implements a lazy permutation. This is a much more robust way than setting the `spatialorder` property of the dictionary.

One thing we do have to decide: should they be "vertical major" (yx) or "horizontal major" (xy)? There are arguments both ways:
- "vertical major" is consistent with the ways that arrays are printed in the REPL. (This dates to a horrible decision to number matrices in row,column order rather than column,row order as would be consistent with Cartesian coordinates. Whoever made that decision back in the 1700s should be chastised mercilessly :smile:.)
- "horizontal major" is what all image libraries like `libpng` and `libjpg` return, and how images are processed in most other languages (I think) besides Matlab. To return a "vertical major" image from ImageMagick, either we have to break the principle of not computing transposes on inputs, or all arrays read by these libraries would be returned as `PermutedDimsArray`s. The problem with the latter is that they'd be row-major, and many algorithms in julia are written to deliver better performance for column-major arrays. It's not a small factor, either (5-fold or so).

I'm torn, so I'm actively seeking advice here. I was going to bring this topic up for discussion once I had all the code and documentation on the new Images basically ready to go. But there's no harm in starting early :smile:.

**Comment by mronian** [comment]
> "horizontal major" is what all image libraries like libpng and libjpg return, and how images are processed in most other languages (I think) besides Matlab. 

I think OpenCV([link](http://docs.opencv.org/2.4/doc/user_guide/ug_mat.html)) and Scikit Image([link](http://scikit-image.org/docs/dev/user_guide/numpy_images.html)) both of which are major and quite popular libraries use vertical major ordering too. Scikit-Image uses numpy arrays as the base Image type. I am in favour of vertical ordering since it would be easier for people looking to switch from other pacakges and also consistent with how other arrays work in Julia.

**Comment by Evizero** [comment]
My personal philosophy is to just go with the language convention. As a programmer who dwells too deep in a quite diverse pool of languages I found that saves me a lot of headache.

Then again, I also see the appeal to go with the domain convention. We have the exact same dilemma in machine learning (which dimension should denote the observations and which should denote the features), and I don't have a perfect answer there either.

So I guess I am of no help at all actually, now that I think about it.

FWIW, one thing I like about the "old" Images.jl is that it just works with what it gets and gives me the image in the form I would expect from the language when I convert it to a plain array.

**Comment by timholy** [comment]
I misunderstood OpenCV, then. I don't know much about Scikit Image. Given that and the fact that Julia itself is vertical-major, it seems like we should go with vertical major.

With ImageMagick.jl, I *guess* we should take a transpose rather than doing it lazily. (I don't know whether one could plausibly load large images via ImageMagick anyway.) And at the least, if we discover this is a mistake, we now have the technology to switch to a lazy-transpose, so it's much easier to correct a poor choice.

**Comment by timholy** [comment]
Having starting looking at Scikit Image's docs a little, I would say that the above discussion didn't quite get it right. Scikit image is, in fact, *horizontal major*; what made this discussion confusing is that it's also *vertical first*. [This link](http://scikit-image.org/docs/dev/user_guide/numpy_images.html#notes-on-array-order) suggests that in python, the "fast dimension" (adjacent memory addresses) corresponds to the last index of the array, whereas in Julia it's first.

I still suspect that we should go with "vertical first," though. I'm less sure about whether we also want "vertical major"; if so, then we'll have to explicitly transpose the output of ImageMagick. I suspect we should just do that, on the assumption that no one is loading huge images with ImageMagick.

**Comment by rsrock** [comment]
My vote is vertical first and vertical major.  Input and output operations are usually the start and end of a long chain of processing steps.  For the intermediate steps, I think it's important to stick with the column major convention of the rest of Julia.  [y x] indexing with the origin in the upper left is also consistent with printing the array at the repl.

**Comment by timholy** [comment]
Closed by #577
