### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tejus-gupta** [JuliaImages/Images.jl#594]
I want to contribute to JuliaImages. I had a look at the proposed roadmap for CameraGeometry.jl  but most of the functionality has already been implemented at https://github.com/peterkovesi/ImageProjectiveGeometry.jl. What new features should I try to add?

I think that methods for optical flow for sparse features and dense optical flow need to be added.

**Comment by timholy** [comment]
That sounds interesting. I'd wager that @peterkovesi's work is not as well-known and well-used as it seems to deserve. If he is willing, it might be a good thing to see what needs to be done to update it for the new API in Images and to add documentation to http://juliaimages.github.io/latest/. Perhaps he'd be willing to collaborate with you on that?

Optical flow utilities would be great to have. In general there's a sparsity of registration/motion estimation tools, though see:
- https://github.com/romainFr/subpixelRegistration.jl
- https://github.com/seung-lab/ImageRegistration.jl

Finally, I just moments ago posted an API comparison page at http://juliaimages.github.io/latest/api_comparison.html#Comparison-with-other-image-processing-frameworks-1. To me the main point of the page is to highlight places where we are missing functionality, so that people like you can see opportunities. Feel free to take inspiration from it, or to add more missing feature-equivalents to that page.

**Comment by peterkovesi** [comment]
I would welcome any collaboration @tejus-gupta .  ImageProjectiveGeometry is totally MATLABesque and has fallen behind the latest developments in the language.  I have been meaning to get back to working on it but other commitments have got in the way.  At the moment I am travelling overseas and will not be able to get back to things for a few weeks yet.  A couple of things I will be adding to the package is a stereo rectification function and some camera calibration code.

**Comment by timholy** [comment]
That's great to hear, @peterkovesi. I also wonder whether any of the camera perspective code would be of mutual interest with GLVisualize.jl? CC @SimonDanisch.

Incidentally, I seem to remember someone posting a fairly long list of missing images functionality in a GitHub issue once; I was planning on incorporating that into the API comparison page, but I've not been able find it. Was it you, @peterkovesi, and if so do you remember where it was?

**Comment by SimonDanisch** [comment]
Yes would be great! I hope my demands for speed and simplicity will match!
I basically just need these:
https://github.com/JuliaGL/GLAbstraction.jl/blob/master/src/GLMatrixMath.jl
at highest speed possible :)

**Comment by peterkovesi** [comment]
@timholy,  I did not make, or have seen, that post on missing images functionality.  
Yes the camera projective code could be of some mutual interest @SimonDanisch .  However, at this stage, my code is very unJulian and slow (embarrassingly so!).  It also has to make provision for lens distortion which messes things up as well.

**Comment by johnnychen94** [comment]
This seems to be an early GSoC discussion and gets outdated now, so I'm closing this. If there's anything related to CameraGeometry and/or ImageProjectiveGeometry.jl, we can still open a new and concrete one.
