### ISSUE TITLE
imgradients doesn't work with KernelFactors.gaussian or IIRgaussian

### ISSUE THREAD

**Issue by yakir12** [JuliaImages/Images.jl#688]
```julia
img = rand(Gray, 5,5)
# works:
imgradients(img, KernelFactors.sobel)
imgradients(img, KernelFactors.prewitt)
imgradients(img, KernelFactors.ando3)
imgradients(img, KernelFactors.ando4)
imgradients(img, KernelFactors.ando5)
# doesn't work:
imgradients(img, KernelFactors.gaussian)
imgradients(img, KernelFactors.IIRGaussian)

ERROR: MethodError: no method matching gaussian(::Tuple{Bool,Bool}, ::Int64)
```

**Comment by zygmuntszpak** [comment]
The `imgradients` function computes the directional change in the intensity or color in an image. 

> Since the intensity function of a digital image is only known at discrete points, derivatives of this function cannot be defined unless we assume that there is an underlying continuous intensity function which has been sampled at the image points. With some additional assumptions, the derivative of the continuous intensity function can be computed as a function on the sampled intensity function, i.e., the digital image. Approximations of these derivative functions can be defined at varying degrees of accuracy. The most common way to approximate the image gradient is to convolve an image with a kernel, such as the Sobel operator or Prewitt operator. [(Wikipedia,Image gradient) ](https://en.wikipedia.org/wiki/Image_gradient) 

[In his paper](https://www.researchgate.net/publication/3193087_Consistent_gradient_operators), Ando Shigeru proposed more accurate kernels for approximating the image gradient. These kernels correspond to `ando3`, `ando4` and `ando5` in Julia.

`imgradients` is not defined for `gaussian` or `IIRGaussian` kernels because convolving the image with those kernels would not result in an approximation of the image gradient.  Instead, these particular kernels are used in `imfilter` for blurring an image.

**Comment by yakir12** [comment]
Sorry, I should have been more specific, in the [documentation](http://juliaimages.github.io/latest/function_reference.html#ImageFiltering.imgradients) of `imgradients` it says:

    `kernelfun` may be one of the filters defined in the `KernelFactors` module

Which lead me to believe that `gaussian` and `IIRGaussian` would also be supported. 

I guess we should adjust the documentation then.

**Comment by zygmuntszpak** [comment]
I've rewritten the documentation of `imgradients` and added two new gradient filters [in this pull request](https://github.com/JuliaImages/ImageFiltering.jl/pull/53).

**Comment by zygmuntszpak** [comment]
We can close this issue since it has been addressed in the aforementioned pull request which has been merged.
