### ISSUE TITLE
Image inpainting

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/Images.jl#702]
I have an implementation of [Crimisini et al.](http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=1323101) and would like to contribute it to the project. It depends on `ImageFiltering.jl` and `ImageMorphology.jl`. I am considering a new package `ImageInpainting.jl` to avoid altering the number of dependencies in other `Images.jl` submodules. Do you think it is a good idea? There are other image inpainting algorithms out there, so maybe a new package could accommodate these variants.

Best,

**Comment by zygmuntszpak** [comment]
I think a separate image inpainting package would be excellent since as you pointed out, there are numerous different techniques for solving this problem.

**Comment by juliohm** [comment]
I will be creating the repository under my profile, please let me know if you would like to have it under the JuliaImages umbrella.

**Comment by juliohm** [comment]
An initial implementation for 2D Julia Arrays is here: https://github.com/juliohm/ImageInpainting.jl

It should work for N-dimensional images, except for [one function](https://github.com/juliohm/ImageInpainting.jl/blob/master/src/utils.jl#L43-L56) that I will fix later. PRs are welcome. :+1: 

Another simple question. How do you erode the borders of an N-dimensional image using ImageFiltering.jl? `padarray` works with negative postpad:

```julia
using ImageFiltering

A = eye(10)
padarray(A, Pad(:symmetric, (0,0), (-1,-1))) # will output 9x9 matrix
```

but it doesn't work with negative prepad:

```julia
padarray(A, Pad(:symmetric, (-1,-1), (0,0))) # will crash
```

**Comment by juliohm** [comment]
Generalized the algorithm for N-dimensional images. I see a lot of places in the code where I am probably doing a suboptimal use of OfsetArrays facilities. Please let me know how these could be improved.

Next steps include handling image types besides Julia arrays.

**Comment by zygmuntszpak** [comment]
Thank you for such a great contribution. I particularly like your use of Unicode! 

`Another simple question. How do you erode the borders of an N-dimensional image using ImageFiltering.jl? padarray works with negative postpad:`

I'm surprised that padding with negative indices actually drops column and rows. I wonder if that is by design or just an unintended consequence? I recently added documentation for the `padarray` function and it didn't even occur to me to use negative indices to remove things. That seems to go against the implication of the word `pad`. Did you genuinely need to drop columns and rows, or was using `views` sufficient?

**Comment by juliohm** [comment]
Thanks @zygmuntszpak for your comment. I guess the negative values in `padarray` are an unintended consequence. Although I used it in other packages, it would be great to either document it properly or provide a different function name in this case.

Going back to the inpainting implementation, there are many things that need to be improved. For instance, I am still a little confused about the role of `parent` that I needed to call [here](https://github.com/juliohm/ImageInpainting.jl/blob/master/src/crimisini.jl#L39-L41) to make the code work.

**Comment by juliohm** [comment]
And answering your last question that I almost missed, I managed to use views instead of dropping rows and columns with `padarray` when I return the result [here](https://github.com/juliohm/ImageInpainting.jl/blob/master/src/crimisini.jl#L90).

**Comment by juliohm** [comment]
@timholy @Evizero I will be registering the package tomorrow under my account after writing a few tests. Please let me know if I should make it part of the JuliaImages organization instead.

Best,

**Comment by Evizero** [comment]
What are your thoughts concerning maintenance of the package?

**Comment by juliohm** [comment]
@Evizero I will maintain it as the other packages I've written. I am fine with keeping the package under my profile as well. Just wanted to double check if there was interest. On a related question, do we have a guideline to decide when to consider a package as part of the organization or as a standalone package? That would help future contributions to stay in the most appropriate place. Since I don't have write access to the organization, I keep bothering you with this question, sorry.

**Comment by Evizero** [comment]
I don't think there is a guideline. I'd say its more of a conversation to give member a opportunity to voice opinions and feedback. In my opinion the packages should be general purpose Image processing. 

Right now my main concern is maintenance, so that we avoid the JuliaML situation of having a couple of dormant, disconnected packages. My experience in image processing is spotty, so I often don't have the skill set to judge domain specific functionality (such as image inpainting). So the main thing I do in such a situation is try to get a sense of what others think. The small thing I can contribute to the conversation is trying to get a feel about the codebase and if it meets a certain maturity standard. I.e. being reasonably structured, documented, and tested. From what I can tell the package meets these except the tested part, which you mentioned you are working on next.

Personally, I think that if you are willing to maintain it I have no reservations against moving the package here for visibility and to attract contributors. I would prefer it to have tests first, though. I can't claim that I quite understand how inpainting connects to the rest of the ecosystem but I have known you for a while and I trust your judgment.

> Since I don't have write access to the organization, I keep bothering you with this question, sorry.

You are not bothering me at all. I am happy to (try to) help on organisational duties where I can, while others are busy with other responsibilities. 

I just set the permissions such that members can create new repositories. I think in general we shouldn't do it out of the blue without asking first, but I don't think there is a reason to disallow it on a strict permission level (given the small number of members)

**Comment by juliohm** [comment]
All very good comments as usual @Evizero, thank you for your work in this community. I will work on the tests, and try to improve the documentation on the README with a few examples as well. After that is done, I will contact you again to transfer the repository to JuliaImages.

**Comment by juliohm** [comment]
Is there any known issue with TestImages.jl on Travis? I am getting a segfault after the images are downloaded: https://travis-ci.org/juliohm/ImageInpainting.jl/jobs/357202750#L759-L774

The tests are successful on my laptop.

**Comment by juliohm** [comment]
The tests are also successful on the Travis Mac build. I don't know the reason for the segfault on Linux Travis.

**Comment by Evizero** [comment]
There logs look like this is a GR issue.

```
while loading /home/travis/.julia/v0.6/ImageInpainting/test/runtests.jl, in expression starting on line 40
__longjmp_chk at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7fa8c0d2550e)
png_error at /lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
png_create_write_struct_2 at /lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
png_create_write_struct at /lib/x86_64-linux-gnu/libpng12.so.0 (unknown line)
unknown function (ip: 0x7fa8c0d25688)
cairo_surface_write_to_png at /home/travis/.julia/v0.6/GR/src/../deps/gr/lib/./cairoplugin.so (unknown line)
unknown function (ip: 0x7fa8c0ce83b7)
gks_cairoplugin at /home/travis/.julia/v0.6/GR/src/../deps/gr/lib/./cairoplugin.so (unknown line)
```

**Comment by juliohm** [comment]
I restarted the build, let's see if the error persists. I will reach the GR devs if it is still present.

**Comment by juliohm** [comment]
@Evizero I've transferred the repository to JuliaImages, could you please activate attobot if it is not activated already?

**Comment by Evizero** [comment]
looks like its activated

**Comment by juliohm** [comment]
Thank you all, the initial release is now available in the organization.
