### ISSUE TITLE
GSoC 2018 Proposal

### ISSUE THREAD

**Issue by arijitkar98** [JuliaImages/Images.jl#707]
I am applying for Google Summer of Code 2018 in JuliaImages. I have prepared the first draft of my proposal. Here is the link to the [proposal](https://docs.google.com/document/d/1qzzx87M5gWDhl8O2jRy3eQ0JkCQkz-yh3uJ6bTXcYLA/edit). I’m still deciding about the timeline and the algorithms. I request all the developers to kindly take some of their valuable time to review it and suggest changes. Any feedback regarding the proposal will be highly appreciated.

**Comment by arijitkar98** [comment]
Ping @zygmuntszpak @Evizero @kmsquire

**Comment by zygmuntszpak** [comment]
I think that you are addressing a real gap in the current API and it will be extremely useful to have implementations of the functions you have outlined. 

Thinking critically, I do have some reservations and suggestions with regard to some of the content of your draft proposal. My impression is that the scope of your project and what you intend to implement may be unrealistic. Perhaps you are taking on too much with unrealistic expectations of how long it might take to actually implement some of this properly? Maybe it would be better to drop the ImageFiltering related work from the proposal and focus primarily on the tracking algorithms. That way you can assign more time to some of the tracking tasks. Also, you are not using a 5-day working week but the whole week for a task. I would prefer to see you plan your workload in the context of a normal 5 day working week and intuitively I feel that implementing some of the tracking work, such as the MIL with test and documentation may take more than just 5 days, perhaps even 8 to 10. When you write your coding period with the dates, please also add how many days a task will take in parenthesis. That way one can check with a quick glance how much time you have allocated. 

I noticed that you broke some of the tasks up in your 'Coding Period' section. For example, you allocated time for implementing the Haar features, and then a different block of time for Adaboost. It would be good to have such a breakdown of subtasks early in your proposal when you introduce the methods you will be implementing. Ideally, I would like to see more details about the key-steps that are required to implement a particular algorithm and I would like to see you identify which steps are more challenging (will require more time) and which ones are straightforward. 

For example, implementing the Lucas Kanade algorithm will require the use of an image pyramid. Does the Julia image package already have this function? If it does (or something similar) then presumably that step will not take time. At some point you will need to solve a system of equations. Do you have an idea of how you would do that? Is this a step which would take a lot of time for you to implement or not? Essentially, I would like to see that you have a reasonably detailed understanding of what is actually involved in implementing an algorithm and that you are have some idea on what is already available for you, and what will need to be coded. 

This reduces the risk that you will get stuck later because you don't understand how to translate the published paper into a working implementation. 

Continuing with another example, what is involved in the MIL tracking part? Do you need to write your own machine learning method? If so, will you need to make use of an optimization package?  

I would also like to see that you have put some thought into how you would test and validate some of these algorithms. For example, how will you test that the optical flow implementation is correct? 

Are you aware of certain tools that Julia provides for evaluating and benchmarking code? For example, the "Traceur.jl" package, or the "BenchmarkTools.jl" package? Can you demonstrate in your proposal that you are aware of how to write fast code (i.e. that have you read the performance tips section of the Julia documentation). 

You might also want to revisit some of your API outline. I understand that it is not the final version, but you might be able to demonstrate that you are familiar with some of the coding standards. For example, functions in Julia are written in lower-case by conventions since upper-case is used for Types. The names of your functions also don't follow the convention. 

Take a look at the [ImageInpainting](https://github.com/juliohm/ImageInpainting.jl/blob/master/src/crimisini.jl) package and how _juliohm_  defined an algorithm type 
```
struct Crimisini{N} <: InpaintAlgo
  psize::Dims{N} # patch size
end
```

and a function
```
function inpaint_impl(img::AbstractArray{T,N}, mask::BitArray{N}, algo::Crimisini{N}) where {T,N}
```
If someone wanted to implement a different method they would just need to specify a new suptype of `InpaintAlgo`. Hence, there isn't a different `inpaint_imp` function name for each possible method. Rather, there is only one  name and dispatch is used to select the appropriate one. 

You could do something similar, with a single function `optical_flow` and specific types that dispatch on the `LK` or the `Farneback` types.

Hope that helps!

**Comment by arijitkar98** [comment]
Thank you so much :smiley: 

I will get to incorporating these in my proposal right away!

**Comment by juliohm** [comment]
Thank you guys for the discussion and plans. I am looking forward to see the progress. I was using optical flow the other day in Python, and really miss it in Julia. Exciting!

**Comment by stillyslalom** [comment]
I implemented an iterative Lucas-Kanade algorithm a while back. It's not pretty or performant, but you're welcome to refer to it if you'd like: https://github.com/stillyslalom/FOLKI.jl/blob/master/src/folki-cpu.jl
