### ISSUE TITLE
GSOC

### ISSUE THREAD

**Issue by PrashantSaroj** [JuliaImages/Images.jl#784]
My name is Prashant Saroj. I am second year Computer Science student. I am willing work on "JuliaImages Projct". How do I get started?

**Comment by johnnychen94** [comment]
Hi Prashant, 

As you might know, I'm also interested in this and I'd like to share how I start(ed).

1. you might want to first read through [Official document](https://juliaimages.org/), try it and have a feeling of what current `Images.jl` provide.
2. Is there anything you find missing and you happen to be interested in. If there is (actually there're a lot), then:
3. check if you've meet the prerequisite, e.g., how might you fix/implement this? have you ever tried doing such things? For example, I'm not familiar with OpenCV so I didn't choose this (even though I'm interested in this)
4. try to create a PR of simple patch and make it merged -- just to have a feeling of how to code with julia and the image ecosystem as well as with this community. -- also find out who you might want to be guided by.
5. after you make sure you really want to propose a GSoC project of Images.jl, draft your idea out and share with us. 

_I'm not your potential mentor_: 
Image processing actually consists of many fields that required very specialized knowledge. Personally, I'm very glad to help you but since we might not share the same interest and background, it's very likely you do this job alone. I think this also holds true for others.

Best wishes

Johnny

**Comment by timholy** [comment]
Sorry for my slow response, I have been swamped with trying to get the new debugger finished. It has been a big job.

We'd love to have you. Johnny's list is great. Learning a bit of Julia (see the "Learning" page at the main site) is obviously a good early step.
