### ISSUE TITLE
GSOC'19

### ISSUE THREAD

**Issue by robotiste** [JuliaImages/Images.jl#789]
Hey @zygmuntszpak @timholy,
I am Vikas Kamboj from Cluster Innovation Centre, University of Delhi, India. I am a 3rd-year B.Tech(Information Technology and Mathematical Innovations) student.

I want to work on "Contributions to a Stereo Matching Package" project under this GSOC. 
I have worked on different applications of stereo vision earlier. 
I have implemented it for very well known competition "University Rover Challenge(URC)" for our rover.
I have implemented it for a self-driving car prototype.
I have also implemented various deep learning models including GANs for predicting accurate depth.
I have implemented from simple Triangulation to various different twist. 
 
I was thinking to complete the first phase of this project before GSoC get started
i.e. Implementation of stereo vision using simple triangulation. 

I will read the papers that are mentioned in the description.
Please let me know your views and please mention if I am going wrong.

Thanks!

**Comment by johnnychen94** [comment]
Looks like you've done a lot of CV-related works. :+1:

I'm a student as well, and there're three points I'd like to mention:

* The student application time: March 25 to April 9. You need to draft your proposal as fast as you can.
* Doing experiments (like you've done) is quite different with contributing codes to `Images.jl` -- you need to write robust code and a bunch of test cases to tell/persuade others your code is amazing.
* @Deepank308 is applying for the same project, you might not want to compete with him -- otherwise, I guess only one of you will be accepted.

**Comment by robotiste** [comment]
Cool! 
Thanks for the information. I am aware of that, also I was following the work over here as well but never create a pull request becuase of my mid-semester exams(like you) till yesterday.
I know I am late, but let's see what all I can contribute.
