### ISSUE TITLE
GSoc 2019 - Project Ideas

### ISSUE THREAD

**Issue by rsnk96** [JuliaImages/Images.jl#791]
Hi everyone!

I know I'm late to start, but I just realized I have some time this Summer to contribute to Julia Images

My profile:
1. Open source: made *minor* contributions to many efforts including `scikit-image`, `nteract`, `torch`, `pytorch`{open PR}, `vscode-python`, etc. Also used CV for a lot of my projects (ref: @rsnk96)
2. Have developed and tested algorithms for [Detect Technologies](https://www.detecttechnologies.com/)
3. Have delivered talks at local Pycon chapters, written some [blogs](https://link.medium.com/sxQKipFBuV), headed and curated content for [iitmcvg](https://github.com/iitmcvg)

I'd like to contribute to Julia Images because I've often realized Julia would be a lot simpler to ideate and deploy in, but there has always been something holding that back from becoming a reality. I'd like to work on a project that bridges that gap. Some such projects are

1. A lot of basic functionality is missing in Julia Images such as basic video processing(meanshift, camshift,etc), blob detection (only LoG is implemented so far), SLIC, seam carving, boundary filling (modification to region growing), graph-cuts(difficult though!!), etc. I am open to suggestion on work that could be done for such module(s)
2. The documentation is lacklustre/non-existent. However, it seems like @johnnychen94 might do good work in that front, and unless two cooks doesn't become too many cooks, I'd leave that broth to him :)

Right now I'm inclined towards implementing some video processing methods. @timholy @zygmuntszpak please let me know your thoughts on the same

**Comment by johnnychen94** [comment]
Hi Nikhil,

Since I'm not familiar with CV, I'd better not saying anything on that.
I started to think about the v1.0 milestone of Images.jl while drafting my GSoC proposal. Here's what I valued as most essential work:

1. unify the API and pruning the codebase -- you can see there're lots of legacy codes here and there
2. enhance `ImageCore`, `Colors` -- currently the traits are not so friendly to new developers
3. documentation, demos, and tutorials
4. implementing missing functions/utils and modules -- if you want to implement new algorithms, [ImageBinarization](https://github.com/zygmuntszpak/ImageBinarization.jl) can be a good inspiration on coding style.
5. optimization and benchmark on performance

and of course, there's some enhancement work that worth doing:

6. GPU support
7. integrate with other libraries, e.g., opencv

As you might know, "pruning the codebase" is included in my GSoC project, and I think I'll do part of 2-4 this summer parallelly. However, since I'm still new to Images.jl, Prof. Tim, Dr. Zygmunt, and @Evizero are more qualified to plot the roadmap.

As for documentation work
* I'm absolutely not the most appropriate person to do this since I'm not a native English speaker. There're cases I might not express myself accurately, which would mislead users. You're very welcomed to take over this job.
* there're never too many cooks to do documentation work.
* As for demos, IMO, the current documentation template https://github.com/JuliaImages/juliaimages.github.io isn't at a good status for introducing new demos. -- No CI integrated.


---

Unfortunately, as you've said, it might be late to apply a GSoC since all of them are quite busy these days. You might want to get in touch with them through slack. I'm looking forward to work with you.

Best Wishes

Johnny

**Comment by rsnk96** [comment]
Thanks for the tips!

I still think that some basic video processing would make for a good project. However, If I have to go forward with documentation as a proposal, it would essentially boil down to a system which automatically generates the documentation from the docstrings, like you mentioned [here](https://github.com/JuliaImages/Images.jl/issues/790), right?
Are you sure you would be okay with me proposing documentation in my proposal? Because both of us proposing it might mean we would be up against one another, and there's enough work that we don't have to do that.

As for the demos, the CI would have to be integrated into the each Julia Images repository directly, wouldn't it. Are you aware of how [scikit-image](http://scikit-image.org/docs/dev/auto_examples/) does it, for instance?

**Comment by johnnychen94** [comment]
I'm not very clear of the documentation detail of `scikit-image` since it uses sphnix. 

Each example of `scikit-image` gallery is generated from only one `.py` file:
[Hierarchical Merging of Region Boundary RAGs](http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_boundary_merge.html#sphx-glr-auto-examples-segmentation-plot-boundary-merge-py) ([source](https://github.com/scikit-image/scikit-image/blob/master/doc/examples/segmentation/plot_boundary_merge.py))

In julia, we have [Literate.jl](https://github.com/fredrikekre/Literate.jl) that can do similar work. We just need someone to figure out how to make it work.

About CI on demos, to make things easier, probably we don't need to check the numeric result, we might just need to make sure there's no warning and error while running the demos. -- CI on source codes is enough to guarantee it.
