### ISSUE TITLE
ImageMagick should be in the [deps] section in Project.toml

### ISSUE THREAD

**Issue by EvertSchippers** [JuliaImages/Images.jl#824]
I use Images.jl **only** to save a jpg image, using this statement:

using Images
...
save("filename.jpg", someUInt8Matrix)

But my project/enviroment needs ImageMagick to be added before this works. I'm not using it myself directly (I don't have a "using ImageMagick" in my code).

Somewhere Images.jl does use it. I should not have to add "ImageMagick" to my project, it should automatically be added to my Manifest when I Pkg.add Images.

You can replicate by temporarily removing your enviroment, add just Images, and try and use it...

**Comment by johnnychen94** [comment]
`FileIO` specifies a set of general file I/O APIs such as `load` and `save`. It doesn't have codes on specific file formats, which means you need to install an image IO package (e.g., `ImageMagick`) to read image files, and `CSV` to read `.csv` files, etc.

Adding `ImageMagick` as a *hard* dependency of `FileIO` might free you from installing it manually *once*, in the cost of adding it for all downstream projects (even for those unrelated to images), so I think this request won't be considered.

> I use Images.jl only to save a jpg image

In this case, you don't need `using Images`, instead `using FileIO` with `ImageMagick` installed is sufficient.

**Comment by timholy** [comment]
Exactly. Moreover, depending on platform the user may prefer different packages (e.g., QuartzImageIO on macs).

**Comment by EvertSchippers** [comment]
You are totally right, I feel a bit stupid... Thanks for responding - and solving this!

**Comment by mbaz** [comment]
This seems related; let me know if you'd prefer that I open a new issue...

I tried following the ["Getting started"](https://juliaimages.org/stable/install/) instructions:

```
using TestImages
img = testimage("mandrill")

Fatal error:
ERROR: ArgumentError: Package ImageMagick not found in current path:
- Run `import Pkg; Pkg.add("ImageMagick")` to install the ImageMagick package.
```

It seems to me like ImageMagick should in fact be installed as a dep of Images.jl...

**Comment by johnnychen94** [comment]
The documentation CI isn't continuously hitting failures during deployment, but you can view the latest version of "getting started" by this: https://juliaimages.org/previews/PR115/install/

**Comment by johnnychen94** [comment]
I believe the reason we didn't do this for Images.jl is that binary dependency was a maintenance nightmare.

Now with the artifact system provided by Julia >= 1.3, bundling a default backend into Images looks like a good choice for me. However, we might not want to do this right now because people here are too busy to maintain two Images versions(one for Julia < v1.3 and one for Julia >= v1.3). We can do this when we upgrade to the next Julia LTS version.

**Comment by timholy** [comment]
Yes, that was written when FileIO installed packages for you.

ImageMagick may be a good choice on Linux, though with ImageIO that's getting less clear. It's even less obviously so on Mac, where QuartzImageIO was at least once the default option.

**Comment by mbaz** [comment]
Thanks! BTW, I only installed ImageMagick.jl because that's what the error message prompted me to do.

**Comment by ianshmean** [comment]
Just bringing this discussion here. 

What would we consider the minimum feature set that ImageIO would need to be _the one_?

**Comment by johnnychen94** [comment]
Adding these backends won't increase the loading time of `Images`, and since adding these backends are no longer a nightmare since Julia 1.3, I think it would be acceptable to add all of them.

`QuartzImageIO` is reserved for macOS and that makes default `load` and `save` behavior different across platforms, keywords arguments are different, too. For this reason, I suggest we don't add `QuartzImageIO` to `Project.toml`.

That said, I think it's would be sufficient to add `ImageMagick` and `ImageIO` into Images' `Project.toml`, and when `ImageIO` has higher priority in the FileIO's registry for every image file types, we're in essence sunsetting `ImageMagick`. A quick look at the registry, I find `GIF`, `JPEG`, `BMP` and `PCX` are supported by `ImageMagick`.

We could add these now, but I prefer to add these in next Julia LTS version by setting Julia compat to `>= 1.3` (or probably newer). Otherwise, Julia 1.0 users might suffer from risks of installing these backends. (I know many users using this Julia version as they feel LTS safer :joy:)

**Comment by johnnychen94** [comment]
In the "State of Julia 2020", YouTube talk. It's officially announced that 1.6 will be the next LTS version, we could add `ImageMagick` and `ImageIO` to the `Project.toml` of Images then.
