### ISSUE TITLE
GSoC introduction

### ISSUE THREAD

**Issue by wizofe** [JuliaImages/Images.jl#876]
I am Ioannis, a very motivated student looking to contribute to Julia Images. I am already using it for my MRes in Medical Imaging at King's College London. Next year I will start my PhD and will explore deep learning approaches for cardiac MRI reconstruction. My plan is to use Julia as my primary language, so I would like to connect with the community and contribute while I am learning.

Having experience in the industry, research and academia for the last 8 years, I am very willing to apply any experience in this project.

Specifically, I am looking for a mentor who can give me some feedback on what would make more sense to implement (i.e. what is most important for the community). Having said that, I believe that the proposed "Wide-ranging demos" is very suitable for me, as I do have done many projects with image processing using MATLAB and Python that would be easily translated to Julia. I am also keen to explore "GPU support for algorithms", using my experience in CUDA programming (although limited to research/coursework).

I am looking forward to hearing from you,

Ioannis aka @wizofe

cc: @timholy @zygmuntszpak

**Comment by timholy** [comment]
Either of those sounds like it would be a major contribution! I'd be very happy to mentor either project. Both of these projects contribute things we desperately need, and offer opportunities to reflect on our overall design while moving forward with actionable improvements. Do you want to give a try to making a PR for one or the other? Traditionally GSoC students have fared best if they get their feet wet before putting together a formal application.

**Comment by johnnychen94** [comment]
Great to hear that you're interested in JuliaImages! 

> I believe that the proposed "Wide-ranging demos" is very suitable for me

Demos in JuliaImages are powered by https://github.com/johnnychen94/DemoCards.jl, which is still under development and might be buggy. If you would like to contribute demos, I'm very willing to offer some help (and bug fixes) related to DemoCards.

> I am also keen to explore "GPU support for algorithms"

Many algorithms in JuliaImages haven't taken advantage of multi-threads and GPU, so this would definitely be a great contribution and would benefit the whole Julia community. (Recently I'm doing some deep learning projects to try to explore the possibility of cooperating Images with Flux seamlessly. The status quo is that we still need to do reshaping and channel splitting/combining operations so that CuArrays understands and not hitting scalar operation, which is extremely slow.)

---

My suggestion is that you can try to familiarize yourself with the JuliaImages' ecosystem by contributing some demos(by doing that we can quickly know how successful your project can be) before the application DDL, and then when you feel comfortable, filling the missing functionality you found(e.g., GPU supports)

**Comment by wizofe** [comment]
Dear @timholy and @johnnychen94. Thank you both for the suggestions. I am going to follow your advice and lookup `DemoCards.jl` so that I can propose some meaningful demos. Give me a few days and I will come with a PR :)
