### ISSUE TITLE
Willing to participate GSoC 

### ISSUE THREAD

**Issue by xiaoerlaigeid** [JuliaImages/Images.jl#878]
I am a first-year master student at Shanghai Jiaotong University. I research areas are medical image analysis and image processing. Julia is a very high efficient language So I plan to learn Julia for image processing. I am interested in contributing to a Stereo Matching Package. I did some relevant project on stereo matching and depth map reconstruction. Wide-ranging demos is also a  good choice, this could help get more familiar with Images.jl
Could any mentors give me some advice? Thanks!

**Comment by timholy** [comment]
That sounds great! Have you used Julia much yet? You might consider picking a simple task to start getting your feet wet. Here are some ideas:
- create one demo with DemoCards
- look for "good first issue" labels on packages
- see if anything in https://github.com/JuliaImages/ImageFiltering.jl/issues/142 seems appealing
- see if @kczimm is interested in help with the new ImageReconstruction.jl (which seems close to your interests), for example https://github.com/JuliaImages/ImageReconstruction.jl/pull/2.

**Comment by johnnychen94** [comment]
It's great to know that Images.jl gets attention from developers in China. I'm willing to give some help and maybe do some co-mentor work.

Having said that, starting to apply for GSoC right now might be a little bit late, but still, let's see if things work out.

First, doing JSoC/GSoC means that you need to participate in the Julia community. Most Julia users use slack to communicate (get an invitation [here](https://slackinvite.julialang.org/)) and there's a #jsoc channel that you might find some information useful. If you find speaking English less comfortable, [JuliaCN](https://cn.julialang.org/) maintains a QQ group 316628299, but note that it's far less informative right now since there are not as many Julia power users in China as in the English world.

Second, you'll need to be familiar with Julia and JuliaImages as quickly as possible. If reading the [official documentation](https://docs.julialang.org/) is too challenging for you, there's a more basic [tutorial in Chinese](https://github.com/hyper0x/JuliaBasics). But you still need to read the Julia docs later. Speaking of JuliaImages, the ecosystem is quite different from what you've experienced in Python, and it's not as mature as OpenCV right now. Hence you'll need to take some adventures reading the slightly outdated documentation https://juliaimages.org/latest/. Usually, using Julia to reimplement something you're familiar with in other languages is a good practice to step.

As Tim says, creating demos using [DemoCards](https://github.com/johnnychen94/DemoCards.jl) might be helpful for you to understand concepts quickly, as well as proving that you have the ability to make JuliaImages better. (For example, https://github.com/JuliaImages/juliaimages.github.io/pull/106 from another student is quite promising to us)

Third, applying GSoC is competitive, thus contributions like bug reports/fixes are usually a requirement. Quoting from Viral Shah (Co-founder and CEO of Julia Computing):

> For all the prospective GSoC students, in order for you to have a successful application, it would be good to show a serious capability with Julia, and make some contributions to the packages you want to work with.
> This gives a much better signal to your mentor in evaluating how successful the GSoC will be

BTW, it's not the case we choose a project idea for you (we can't), it's you find a project that you're willing to take care of and that benefits the community. Ideas in https://julialang.org/jsoc/gsoc/images/ are just a subset of what we're looking forward to seeing. If you have great ideas, feel free to share it with us.

---

P.S. There're always some misunderstandings about GSoC and mentor. Just in case you're not aware, doing GSoC is more or less your own project -- mentors don't code for you, instead, they give advice and check your project schedule. (Unlike students, mentors don't get funded, though)

P.S. SJTU is near to ECNU, feel free to get in touch with me when the NCP is over. I do have plans to do some Julia tutorial for students here.

P.S. The network/GFW issue might be amplified when you're doing GSoC. You'll need to prepare a stable proxy (or maybe more) to use google, AWS, and Github.

**Comment by xiaoerlaigeid** [comment]
@timholy @johnnychen94  Many thanks for your replys. I will get started to go through JuliaImages as quickly as possible. I will back!

**Comment by kczimm** [comment]
@xiaoerlaigeid, feel free to reach out if you find image reconstruction appealing.

**Comment by xiaoerlaigeid** [comment]
@kczimm sorry for replay late. Recently I have been familiar with Julia and the image processing library. If I want to do the image reconstruction project what should I do?
