### ISSUE TITLE
GSOC student Introduction

### ISSUE THREAD

**Issue by nairitya03** [JuliaImages/Images.jl#881]
Hi , I am Nairitya Tale pre-final Undergrad Student from india.
Its my first time entering GSOC and have absolutely no knowledge how to oe what start with.

I have been working with python and Computer Vision (OpenCV) for sometime and is keenly interested to explore the vast field of Computer Vision. With my prior knowledge have built acute project. And Willing to step forward in the direction of computer vision and detection be it faces, objects, number plates or anything and heard heard about Julia and Juliaimages and as Julia is a rapid growing and bit fast processing language I would like to work on it.

Guidelines or suggestions would be of much help .
And would also love to have a mentor who can guide me throughout my journey.

Thanks

**Comment by timholy** [comment]
Welcome @nairitya03! I'd recommend you think about us for GSoC 2021; at this point there is very little chance you'd be accepted, since we expect students to demonstrate a commitment to the ecosystem before we recommend them. Most successful applicants show up at least a month in advance and start making pull requests as a means of demonstrating their abilities and giving them time to put together a realistic application. We have found that this leads to excellent outcomes, as witnessed by previous student's contributions and future career trajectories.

So please do keep us in mind for 2021!

**Comment by nairitya03** [comment]
Any suggestions how to get up and running with Juliaimages and get to the point of recommendations for next year.

**Comment by timholy** [comment]
Perhaps the best place is Julia's own learning materials (https://julialang.org/) followed by the JuliaImages documentation (https://juliaimages.org/latest/). I hope/expect the latter in particular to improve a lot over the course of the next year but hopefully it's at least decent already.

After that, look for simple issues to use to get your feet wet. I'm trying to be better about marking some issues as being good for beginners (examples tagged at https://github.com/JuliaImages/ImageFiltering.jl/issues), and if some people show up and tackle them it will be extra incentive to think about this more often.
