### ISSUE TITLE
Error loading images

### ISSUE THREAD

**Issue by mdav2** [JuliaImages/Images.jl#889]
Simply trying to load an image using `load` causes the following error on my machine. I had this working just yesterday, but I have not been able to figure out what has changed. Any help would be greatly appreciated!

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0 (2020-03-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Images
[ Info: Precompiling Images [916415d5-f1e6-5110-898d-aaa5f9f070e0]

julia> load("ohsu.jpg")
[ Info: Precompiling ImageMagick [6218d12a-5da1-5696-b52f-db25d2ecc6d1]
WARNING: both ImageMagick_jll and Base export "convert"; uses of it in module ImageMagick must be qualified
Error encountered while loading "/home/mmd01986/Dropbox/3_Projects/dtb/packages/LoopVectorization/ohsu.jpg".

Fatal error:
ERROR: UndefVarError: convert not defined
Stacktrace:
 [1] handle_error(::UndefVarError, ::FileIO.File{FileIO.DataFormat{:JPEG}}) at /home/mmd01986/.julia/packages/FileIO/Glbhe/src/error_handling.jl:82
 [2] handle_exceptions(::Array{Any,1}, ::String) at /home/mmd01986/.julia/packages/FileIO/Glbhe/src/error_handling.jl:77
 [3] load(::FileIO.Formatted; options::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/mmd01986/.julia/packages/FileIO/Glbhe/src/loadsave.jl:189
 [4] load at /home/mmd01986/.julia/packages/FileIO/Glbhe/src/loadsave.jl:169 [inlined]
 [5] #load#13 at /home/mmd01986/.julia/packages/FileIO/Glbhe/src/loadsave.jl:118 [inlined]
 [6] load(::String) at /home/mmd01986/.julia/packages/FileIO/Glbhe/src/loadsave.jl:118
 [7] top-level scope at REPL[2]:1

```

**Comment by zygmuntszpak** [comment]
I just encountered the same error. It looks like the problem was fixed here: https://github.com/JuliaIO/ImageMagick.jl/commit/c347fb978f2f1353b170c90f70e9eeb11850c597

In principle, the latest version of ImageMagick (version 1.1.5) should resolve this error for your. I'm actually not sure which package in the Julia/Julia Images ecosystem automatically loads the ImageMagick package. Presumably, just doing an update of your packages should fix the problem.

```julia
] up
```

Alternatively, you can explicitly add the `ImageMagick` package to your environment which should pull the latest version for you.

```julia
] add ImageMagick
```

You can verify that you have version 1.1.5 by typing 
```julia
] st
``` 
one you have added the ImageMagick package.

**Comment by johnnychen94** [comment]
The problem is introduced by the new `ImageMagick_jll` build: https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl/commit/d706c5d103320ef23a40f7c2d03da13326cbb156 that accidentally causes a name conflict.

>  I'm actually not sure which package in the Julia/Julia Images ecosystem automatically loads the ImageMagick package.

It's the `FileIO`(IO frontend) that "requires" `ImageMagick`(IO backend). Ref: https://juliaimages.org/dev/install/#Loading-your-first-image-1

```julia
(@v1.4) pkg> st ImageMagick
Status `~/.julia/environments/v1.4/Project.toml`
  [6218d12a] ImageMagick v1.1.5
```

**Comment by mdav2** [comment]
Thank you for the help!
