### ISSUE TITLE
slow JPEG loading

### ISSUE THREAD

**Issue by Sixzero** [JuliaImages/Images.jl#960]
Image reading, specifically ".jpg" is pretty slow, even a workaround with python opencv outperforms the simple load function by 10x.

```
using PyCall
cv2 = pyimport("cv2")
img_path = "testimg.jpg"
py_load(f) = begin
	imgpy::Array{UInt8, 3} = cv2[:imread](f)
	arr = Matrix{RGB{N0f8}}(undef, size(imgpy)[1:2]...)
	n_img = N0f8.(imgpy./255)
	@inbounds for i in 1:size(arr, 1)
		for j in 1:size(arr, 2)
			arr[i, j] = RGB{N0f8}(n_img[i,j,3], n_img[i,j,2], n_img[i,j,1])
		end
	end
	arr
end

@btime load(img_path)
#  1.443 s (48000093 allocations: 1.64 GiB)
@btime py_load(img_path)
#  111.280 ms (40 allocations: 34.33 MiB)
```
Am I missing something, or simple ".jpg" loads are implemented inefficiently?

I am on julia1.7 nightly, and just installed Images.jl package to test speeds. 
I saw other related issues #747 and many others, but they got closed with minor improvements.

**Comment by johnnychen94** [comment]
Currently `jpg` is loaded via the Julia wrapper of [`ImageMagick.jl`](https://github.com/JuliaIO/ImageMagick.jl). I don't know if it's the Julia wrapper that makes it slow, or the `ImageMagick` itself that is slow.

For other commonly used formats such as `png`, `tif`, they're supported by ImageIO, where you can find the benchmark in https://github.com/JuliaIO/ImageIO.jl/issues/21

**Comment by Sixzero** [comment]
Interesting I would like to know how you could find the function which is getting called, I did a small research with @edit calls, but didn't get too far. 
I am pretty sure using pycall for img load is just considered a bad practice, so the above soultion should not be implemented in this lib, but we should strive for better solutions. I read there is libjpg and turbo-libjpg, I would like to know how to implement and use such a solution. :)

**Comment by johnnychen94** [comment]
> I read there is libjpg and turbo-libjpg, I would like to know how to implement and use such a solution. 

There're approximately three steps:

1. cross-compiling the C library (say, `libjpeg-turbo`) for multiple targets using https://github.com/JuliaPackaging/BinaryBuilder.jl, register the compiling scripts in https://github.com/JuliaPackaging/Yggdrasil and make a `libjpeg-turbo_jll` release.
2. write the Julia part of the wrapper, say, `JPEGFiles.jl`, and release it
3. register in FileIO (and in ImageIO) so that `JPEGFiles` has higher priority when users call `load("xxx.jpg")`.

As an example, you can find how png files are supported via [libpng_jll build script](https://github.com/JuliaPackaging/Yggdrasil/blob/a7ee13b0bb644bda92ffd89f6e040df0d41f1041/L/libpng/build_tarballs.jl), [libpng_jll](https://github.com/JuliaBinaryWrappers/libpng_jll.jl) and [PNGFiles.jl](https://github.com/JuliaIO/PNGFiles.jl). @IanButterworth (who wrote PNGFiles) knows more than I do so I believe he can provide more help here.

**Comment by giordano** [comment]
1. has been already done long time ago: https://github.com/JuliaBinaryWrappers/JpegTurbo_jll.jl
